[tool.poetry]
name = "manga_merge"
version = "0.1.0"
description = ""
authors = ["Almas Baktubayev"]

[tool.poetry.dependencies]
python = "^3.8"
pillow = "^7.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
